# Generated by Django 5.0.1 on 2024-02-03 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0009_remove_chatgpt_teamleadphone_chatgpt_transactionid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgpt',
            name='team_Lead_Phone',
            field=models.CharField(default='DEFAULT_PHONE_VALUE', max_length=11, validators=[django.core.validators.RegexValidator(regex='^[0-9]{11}$')]),
        ),
    ]
