# Generated by Django 5.0.1 on 2024-02-03 00:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0010_chatgpt_team_lead_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgpt',
            name='team_Lead_Phone',
            field=models.CharField(blank=True, default='', max_length=11, validators=[django.core.validators.RegexValidator(regex='^[0-9]{11}$')]),
        ),
    ]
